unstable_features = true
edition = "2024"
style_edition = "2024"
max_width = 100
comment_width = 100
group_imports = "One"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
format_macro_matchers = true
wrap_comments = true
newline_style = "Unix"
error_on_line_overflow = true
error_on_unformatted = true
use_field_init_shorthand = true
use_try_shorthand = true
hex_literal_case = "Lower"
float_literal_trailing_zero = "IfNoPostfix"
